#!/home/ac14037/bin/Rscript

setwd("/home/ac14037/project.phd.main")
source("rotation1scripts_v4/scripts/r/functions.R")
source("rotation1scripts_v4/scripts/r/modelling/recombination.modelling.R")

args = commandArgs(trailingOnly = T)
path1 = "rotation1scripts_v4/original_data/simulation/pedigreesim/axcf6.sims/"

file1 = args[1]

load(p(path1, file1))

no.selec.flag = grep("noselec", file1)



if(length(no.selec.flag) > 0){
	analysis1 = perform.analysis(all.sim.files, recombination.position = "AxC1A", F2 = F, fgen = 6)
} else {
	g = strsplit(file1, "selec")
	g = strsplit(g[[1]][2], "pop")
	g = g[[1]][1]
	g = as.numeric(g)
	analysis1 = perform.analysis(all.sim.files, T, 200, g, "AxC1A", F, 6)
}

write.csv(analysis1, p("rotation1scripts_v4/original_data/simulation/pedigreesim/", file1, ".analysis.csv"), row.names = F)


# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2.noselec.pop10000")
# axcf2.noselec.pop10000.analysis = perform.analysis(all.sim.files, recombination.position = "AxC1A", F2 = T, fgen = 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2.noselec.pop96")
# axcf2.noselec.pop96.analysis = perform.analysis(all.sim.files, recombination.position = "AxC1A", F2 = T, fgen = 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2.noselec.pop1000")
# axcf2.noselec.pop1000.analysis = perform.analysis(all.sim.files, recombination.position = "AxC1A", F2 = T, fgen = 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2.noselec.pop300")
# axcf2.noselec.pop300.analysis = perform.analysis(all.sim.files, recombination.position = "AxC1A", F2 = T, fgen = 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec10pop1000")
# axcf2selec10pop1000.analysis = perform.analysis(all.sim.files, T, 200, 10, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec10pop300")
# axcf2selec10pop300.analysis = perform.analysis(all.sim.files, T, 200, 10, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec12pop1000")
# axcf2selec12pop1000.analysis = perform.analysis(all.sim.files, T, 200, 12, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec12pop300")
# axcf2selec12pop300.analysis = perform.analysis(all.sim.files, T, 200, 12, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec14pop1000")
# axcf2selec14pop1000.analysis = perform.analysis(all.sim.files, T, 200, 14, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec14pop300")
# axcf2selec14pop300.analysis = perform.analysis(all.sim.files, T, 200, 14, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec16pop1000")
# axcf2selec16pop1000.analysis = perform.analysis(all.sim.files, T, 200, 16, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec16pop300")
# axcf2selec16pop300.analysis = perform.analysis(all.sim.files, T, 200, 16, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec18pop1000")
# axcf2selec18pop1000.analysis = perform.analysis(all.sim.files, T, 200, 18, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec18pop300")
# axcf2selec18pop300.analysis = perform.analysis(all.sim.files, T, 200, 18, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec20pop1000")
# axcf2selec20pop1000.analysis = perform.analysis(all.sim.files, T, 200, 20, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec20pop300")
# axcf2selec20pop300.analysis = perform.analysis(all.sim.files, T, 200, 20, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec2pop1000")
# axcf2selec2pop1000.analysis = perform.analysis(all.sim.files, T, 200, 2, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec2pop300")
# axcf2selec2pop300.analysis = perform.analysis(all.sim.files, T, 200, 2, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec4pop1000")
# axcf2selec4pop1000.analysis = perform.analysis(all.sim.files, T, 200, 4, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec4pop300")
# axcf2selec4pop300.analysis = perform.analysis(all.sim.files, T, 200, 4, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec6pop1000")
# axcf2selec6pop1000.analysis = perform.analysis(all.sim.files, T, 200, 6, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec6pop300")
# axcf2selec6pop300.analysis = perform.analysis(all.sim.files, T, 200, 6, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec8pop1000")
# axcf2selec8pop1000.analysis = perform.analysis(all.sim.files, T, 200, 8, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec8pop300")
# axcf2selec8pop300.analysis = perform.analysis(all.sim.files, T, 200, 8, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec10pop10000")
# axcf2selec10pop10000.analysis = perform.analysis(all.sim.files, T, 200, 10, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec10pop96")
# axcf2selec10pop96.analysis = perform.analysis(all.sim.files, T, 200, 10, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec12pop10000")
# axcf2selec12pop10000.analysis = perform.analysis(all.sim.files, T, 200, 12, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec12pop96")
# axcf2selec12pop96.analysis = perform.analysis(all.sim.files, T, 200, 12, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec14pop10000")
# axcf2selec14pop10000.analysis = perform.analysis(all.sim.files, T, 200, 14, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec14pop96")
# axcf2selec14pop96.analysis = perform.analysis(all.sim.files, T, 200, 14, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec16pop10000")
# axcf2selec16pop10000.analysis = perform.analysis(all.sim.files, T, 200, 16, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec16pop96")
# axcf2selec16pop96.analysis = perform.analysis(all.sim.files, T, 200, 16, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec18pop10000")
# axcf2selec18pop10000.analysis = perform.analysis(all.sim.files, T, 200, 18, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec18pop96")
# axcf2selec18pop96.analysis = perform.analysis(all.sim.files, T, 200, 18, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec20pop10000")
# axcf2selec20pop10000.analysis = perform.analysis(all.sim.files, T, 200, 20, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec20pop96")
# axcf2selec20pop96.analysis = perform.analysis(all.sim.files, T, 200, 20, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec2pop10000")
# axcf2selec2pop10000.analysis = perform.analysis(all.sim.files, T, 200, 2, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec2pop96")
# axcf2selec2pop96.analysis = perform.analysis(all.sim.files, T, 200, 2, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec4pop10000")
# axcf2selec4pop10000.analysis = perform.analysis(all.sim.files, T, 200, 4, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec4pop96")
# axcf2selec4pop96.analysis = perform.analysis(all.sim.files, T, 200, 4, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec6pop10000")
# axcf2selec6pop10000.analysis = perform.analysis(all.sim.files, T, 200, 6, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec6pop96")
# axcf2selec6pop96.analysis = perform.analysis(all.sim.files, T, 200, 6, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec8pop10000")
# axcf2selec8pop10000.analysis = perform.analysis(all.sim.files, T, 200, 8, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()
# print("loading next object")
# load("rotation1scripts_v4/original_data/simulation/pedigreesim/simresults/axcf2selec8pop96")
# axcf2selec8pop96.analysis = perform.analysis(all.sim.files, T, 200, 8, "AxC1A", T, 2)
# rm(all.sim.files)
# gc()



# all.analyses = list(axcf2.noselec.pop10000.analysis, axcf2.noselec.pop96.analysis, axcf2.noselec.pop1000.analysis, axcf2.noselec.pop300.analysis, axcf2selec10pop1000.analysis, axcf2selec10pop300.analysis, axcf2selec12pop1000.analysis, axcf2selec12pop300.analysis, axcf2selec14pop1000.analysis, axcf2selec14pop300.analysis, axcf2selec16pop1000.analysis, axcf2selec16pop300.analysis, axcf2selec18pop1000.analysis, axcf2selec18pop300.analysis, axcf2selec20pop1000.analysis, axcf2selec20pop300.analysis, axcf2selec2pop1000.analysis, axcf2selec2pop300.analysis, axcf2selec4pop1000.analysis, axcf2selec4pop300.analysis, axcf2selec6pop1000.analysis, axcf2selec6pop300.analysis, axcf2selec8pop1000.analysis, axcf2selec8pop300.analysis, axcf2selec10pop10000.analysis, axcf2selec10pop96.analysis, axcf2selec12pop10000.analysis, axcf2selec12pop96.analysis, axcf2selec14pop10000.analysis, axcf2selec14pop96.analysis, axcf2selec16pop10000.analysis, axcf2selec16pop96.analysis, axcf2selec18pop10000.analysis, axcf2selec18pop96.analysis, axcf2selec20pop10000.analysis, axcf2selec20pop96.analysis, axcf2selec2pop10000.analysis, axcf2selec2pop96.analysis, axcf2selec4pop10000.analysis, axcf2selec4pop96.analysis, axcf2selec6pop10000.analysis, axcf2selec6pop96.analysis, axcf2selec8pop10000.analysis, axcf2selec8pop96.analysis)

# s(all.analyses, "rotation1scripts_v4/saved.objects/ped.sim.f2.analyses", "11042019.pedigree.sim.analyses.R")


