#testing pergola function on Rowenna data
setwd("C:/Users/ac14037/Google Drive/R/scripts/rotation1scripts/")


#data("simTetra") #PERGOLA TEST DATASET

#first need to format data appropriately for pergola
data2=read.csv("chromosomes_preordering_quad1/chr_16_pre-ord.csv", header=TRUE, stringsAsFactors = F) 
data2=cbind(data2[,1],data2)
data2=data2[-2,-1]
data2[data2 == "A"]=as.numeric(0)
data2[data2 == "H"]=as.numeric(1)
data2[data2 == "B"]=as.numeric(2)
data2[data2 == "-"]=2
data2=data2[-1,]
data2=data2[,-1]
#rownames(data2)=data2$probeset_id
data2=t(data2)
data2=data2[-1,]
mode(data2) = "numeric" #CONVERT STORAGE MODE OF DF FROM CHARACTER TO NUMERIC (NB. data.matrix doesn't work — why?)
#now data should be ready for pergola


rf=calcRec(data2, ploidy=2)
split=splitChr(rf, nchr=1)

#get rQTL ordered markers and manipulate into a PERGOLA split object for chromosome designation
rordered=read.csv("allchrpost_quad1.csv", header=F)
rordered=t(rordered[1:3,])
rordered=rordered[-c(1,2,3),]

rownames(rordered)=rordered[,1]
colnames(rordered)=c("names","split","dup")

for(i in 1:nrow(rordered)){
    rordered[i,3]=0
}

str(rordered)
str(split)

#make recombination fraction image
# image(rf, xaxt = 'n', yaxt = 'n')
# axis(side = 1, at = seq(0, 1, length.out = nrow(rf)),
#            labels = rownames(rf), las = 2, cex.axis = 0.8)
# axis(side = 2, at = seq(0, 1, length.out = nrow(rf)),
#            labels = rownames(rf), las = 2, cex.axis = 0.8) 

#pergola sortLeafs function doesn't like my rordered dataframe... try replacing split values generated by pergola with values from my df
for(i in 1:nrow(split)){
    split[i,2]=rordered[i,2]
}

#convert split column to numeric
split$split=as.numeric(as.character(split$split))

#take away 1 from all groups in split column (before they began at 2, i don't think the sortLeafs() function liked it)
for(i in 1:nrow(split)){
    split[i,2]=(split[i,2]-1)
}


plotRf(rf)
plotRf(rf, plottype = "image")


#table(split$split)

split=sortLeafs(rf, split)


maps=pullMap(rf,rordered)
?pullMap
rf
